name: ci-cd

on:
  push:
    branchs:
      - "cicd"
      - "main"
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
jobs:


#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Setup java
#        uses: actions/setup-java@v3
#        with:
#          distribution: corretto
#          java-version: 17
#      - name: Test
#        run: ./gradlew test



  build:
#    needs: "test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Build
        run: ./gradlew build
      - name: Copy jar file to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: esop-trading-1.0
          path: build/libs/esop-0.1-all.jar


  deploy:
    needs: [ "build" ]
    runs-on: ubuntu-latest
    steps:
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Download jar file
        uses: actions/download-artifact@v3
        with:
          name: esop-trading-1.0

      - name: Copy jar file to ec2 instance

        run: |
          eval `ssh-agent`
          aws s3 cp s3://gurukul-vishal-bucket/ip.txt ./
          cat ip.txt
          
          
          ssh_host=$(cat ip.txt | tr -d '"')  
          
          echo  $ssh_host
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          scp -o StrictHostKeyChecking=no "esop-0.1-all.jar" ec2-user@$ssh_host:~
          ssh -o StrictHostKeyChecking=no ec2-user@$ssh_host -t "sudo yum install java-17-amazon-corretto -y"
          ssh -o StrictHostKeyChecking=no ec2-user@$ssh_host -t "sudo fuser -k 80/tcp;sudo MICRONAUT_SERVER_PORT=80 java -jar esop-0.1-all.jar >/dev/null &"



  
  
  
  
