name: create-infra

on:
  push:
    branch: "infra"

jobs:
#  terraformS3:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        shell: bash
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Install Terraform
#        run: |
#          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
#          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
#          sudo apt update && sudo apt install terraform
#      - name: Terraform Init
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: |
#          cd terraform
#          cd s3
#          terraform init
#
#      - name: Terraform Plan
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: |
#          cd terraform
#          cd s3
#          terraform plan
#
#      - name: Terraform Apply
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: |
#          cd terraform
#          cd s3
#          terraform apply -auto-approve
#
#  terraformEC2:
#    runs-on: ubuntu-latest
#
#    defaults:
#      run:
#        shell: bash
#
#    outputs:
#      public_ip: ${{steps.ip_address.outputs.ip}}
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Install Terraform
#        run: |
#          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
#          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
#          sudo apt update && sudo apt install terraform
#      - name: Terraform Init
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: |
#          cd terraform
#          cd ec2
#          terraform init
#
#      - name: Terraform Plan
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: |
#          cd terraform
#          cd ec2
#          terraform plan
#
#      - name: Terraform Apply
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: |
#          cd terraform
#          cd ec2
#          terraform apply -auto-approve
#
#      - name: Export IP Address to environment variable
#        id: ip_address
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: |
#          cd terraform
#          cd ec2
#          echo ip=$(terraform output instance_public_ip | sed 's/^.//;s/.$//') >> $GITHUB_OUTPUT
#

 cicdn:

    uses: sahajvishal898/esop-cicd/.github/workflows/cicd.yml@cicd